CREATE DATABASE QUANLISACH
USE QUANLISACH
CREATE TABLE LOAISACH
(
	MALOAI NCHAR(5),
	TENLOAI NVARCHAR(50)
	PRIMARY KEY (MALOAI)
)
CREATE TABLE SACH
(
	MASACH NCHAR(5),
	TUASACH NVARCHAR(50),
	TACGIA NVARCHAR(50),
	MALOAI NCHAR(5)
	--CACH 1
	CONSTRAINT FK_SACH_LOAIMA FOREIGN KEY (MALOAI) REFERENCES LOAISACH(MALOAI)
)
--CACH 2
--ALTER TABLE SACH ADD CONSTRAINT FK_SACH_LOAIMA FOREIGN KEY (MALOAI) REFERENCES LOAISACH(MALOAI)

--BAI 2
CREATE DATABASE QUANLIHOINGHIKHOAHOC
USE QUANLIHOINGHIKHOAHOC
CREATE TABLE BAIBAOCAO
(
	MABAOCAO NCHAR(5),
	TUABAOCAO NVARCHAR(50),
	TACGIA NVARCHAR(50)
	PRIMARY KEY (MABAOCAO)
)

CREATE TABLE PHIENBAOCAO
(
	MAPHIEN NCHAR(5) PRIMARY KEY,
	NGAY DATE,
	GIOBATDAU TIME,
	MACHUDE NCHAR(5),
	SOLUONGBAOCAO INT
)

CREATE TABLE CHUDE
(
	MACHUDE NCHAR(5) PRIMARY KEY,
	TENCHUDE NVARCHAR(50)
)

CREATE TABLE DANGKY
(
	MABAOCAO NCHAR(5),
	MACHUDE NCHAR(5)
	PRIMARY KEY (MABAOCAO,MACHUDE)
)

CREATE TABLE LICHBAOCAO
(
	MABAOCAO NCHAR(5),
	MAPHIEN NCHAR(5)
	PRIMARY KEY(MABAOCAO,MAPHIEN)
)

ALTER TABLE DANGKY ADD CONSTRAINT FK_DANGKY_BAIBAOCAO FOREIGN KEY (MABAOCAO) REFERENCES BAIBAOCAO(MABAOCAO)
ALTER TABLE DANGKY ADD CONSTRAINT FK_DANGKY_CHUDE FOREIGN KEY (MACHUDE) REFERENCES CHUDE(MACHUDE)
ALTER TABLE LICHBAOCAO ADD CONSTRAINT FK_LICHBAOCAO_BAIBAOCAO FOREIGN KEY (MABAOCAO) REFERENCES BAIBAOCAO(MABAOCAO)
ALTER TABLE LICHBAOCAO ADD CONSTRAINT FK_LICHBAOCAO_PHIENBAOCAO FOREIGN KEY (MAPHIEN) REFERENCES PHIENBAOCAO(MAPHIEN)

ALTER TABLE LICHBAOCAO ADD THOIGIAN TIME
ALTER TABLE LICHBAOCAO DROP COLUMN THOIGIAN
--BAI 3
CREATE DATABASE QUANLIKHO
USE QUANLIKHO
CREATE TABLE NHANVIEN
(
	MANV NCHAR(5) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	NGAYSINH DATE,
	PHAI BIT,
	DIACHI NVARCHAR(50),
	BIENCHE BIT,
	NGAYBATDAU DATE,
	LUONGCOBAN INT,
	GHICHU NVARCHAR(50),
	HINH BINARY
)
CREATE TABLE NHAPXUAT
(
	STT INT PRIMARY KEY,
	NGAY DATE,
	PHIEU NCHAR(50),
	HOTEN NVARCHAR(50),
	LYDO NVARCHAR(50),
	MAKHO NCHAR(5),
	MAVT NCHAR(5),
	SOLUONG INT,
	TIEN INT,
	MANV NCHAR(5)
)
CREATE TABLE VATTU
(
	MAVT NCHAR(5) PRIMARY KEY,
	TENVATTU NVARCHAR(50),
	QUICACH NVARCHAR(50),
	DONVITINH NVARCHAR(50)
)

CREATE TABLE KHO
(
	MAKHO NCHAR(5) PRIMARY KEY,
	TENKHO NVARCHAR(50),
	DIACHIKHO NVARCHAR(50)
)
ALTER TABLE NHAPXUAT ADD CONSTRAINT FK_NHAPXUAT_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE NHAPXUAT ADD CONSTRAINT FK_NHAPXUAT_VATTU FOREIGN KEY (MAVT) REFERENCES VATTU(MAVT)
ALTER TABLE NHAPXUAT ADD CONSTRAINT FK_NHAPXUAT_KHO FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO)

--XOA KHOA NGOAI
ALTER TABLE NHAPXUAT 
DROP CONSTRAINT FK_NHAPXUAT_NHANVIEN
--XOA BANG
DROP TABLE NHANVIEN

--CAU 1
ALTER TABLE NHAPXUAT
ADD CONSTRAINT SOLG
DEFAULT 1
FOR SOLUONG

ALTER TABLE NHAPXUAT
ADD CONSTRAINT Tien
DEFAULT 0
FOR TIEN

--cach khac
/*ALTER TABLE NHAPXUAT 
ALTER COLUMN SOLUONG INT DEFAULT 1,
ALTER COLUMN TIEN INT DEFAULT 0;*/


--CAU 2
ALTER TABLE NHANVIEN
ADD CONSTRAINT CHK_1
CHECK (DATEDIFF(YY, NGAYSINH, NGAYBATDAU) >= 18 AND DATEDIFF(YY, NGAYSINH, NGAYBATDAU) <= 60)

--CAU 3
--KHONG XOA VI VI MAC KHOA NGOAI VOI NHAPXUAT NEN TA XOA KHOA TRUOC ROI MOI XOA DUOC BANG
ALTER TABLE NHANVIEN
ALTER COLUMN PHAI VARCHAR(3)
UPDATE NHANVIEN SET PHAI = CASE WHEN PHAI = 'TRUE' THEN 'YES' ELSE 'NO' END;

SELECT (CASE WHEN PHAI = 'YES' THEN 'NAM' ELSE 'NU' END) FROM NHANVIEN
SELECT * FROM NHANVIEN