use QLSV
go
--BAI 1
ALTER PROC SPCHUOI2 @KHOA NVARCHAR(50)
AS
BEGIN
	PRINT 'DAI HOC CONG NGHE SAI GON '+@KHOA
END
GO
EXEC SPCHUOI2 'CONG NGHE THONG TIN'

--BAI 2
CREATE PROC SPTB @A INT , @B INT , @C INT
AS
BEGIN
	DECLARE @MAX INT = @A
	IF @MAX < @B
		BEGIN
			SET @MAX = @B
		END
	IF @MAX < @C
		BEGIN
			SET @MAX = @C
		END
	PRINT 'SO LON NHAT TRONG 3 SO LA: ' + CONVERT(CHAR,@MAX)
END
GO
EXEC SpTB 4,2,3

--BAI 3
CREATE PROC SPTONGDAY @N INT
AS
BEGIN
	DECLARE @I INT = 1
	WHILE @I <= @N
		BEGIN
			PRINT @I
			SET @I = @I +1
		END
END
GO
EXEC SPTONGDAY 5

--BAI 3
ALTER PROC SPSONGUYENTO @N INT
AS
BEGIN
	IF @N >= 2
	BEGIN
		DECLARE @I INT = 2
		WHILE @I <= @N
		BEGIN
				DECLARE @J INT = 1, @COUNT INT = 0			
				WHILE @J <= @I
				BEGIN
					IF @I % @J = 0
						SET @COUNT += 1
					SET @J += 1
				END
				IF @COUNT = 2
				BEGIN
					PRINT @I
				END
				SET @I += 1
		END
	END
	ELSE
		PRINT CONVERT(NVARCHAR(5),@N) + ' KHONG PHAI LA SO NGUYEN TO'
END
GO
EXEC SPSONGUYENTO 1

--BAI 4
ALTER PROC SPPTBAC2 @A FLOAT, @B FLOAT, @C FLOAT
AS
BEGIN
	IF @A = 0 
	BEGIN
		IF @B = 0
		BEGIN
		 IF @C = 0
			PRINT 'PHUONG TRINH VO SO NGHIEM'
		 ELSE
			PRINT 'PHUONG VO NGHIEM'
		END
		ELSE
			PRINT 'PHUONG TRINH CO NGHIEM DUY NHAT LA: ' + CONVERT(NCHAR(5),-@C/@B)
	END

	ELSE
	BEGIN
		DECLARE @DELTA FLOAT = @B*@B - 4*@A*@C
		IF @DELTA > 0
		BEGIN
			DECLARE @X1 FLOAT = (-@B+SQRT(@DELTA))/(2*@A)
			DECLARE @X2 FLOAT = (-@B-SQRT(@DELTA))/(2*@A)
			PRINT 'NGHIEM THU NHAT LA: ' + CONVERT(CHAR,@X1)
			PRINT 'NGHIEM THU NHAT LA: ' + CONVERT(CHAR,@X2)
			RETURN 0
		END
		IF @DELTA = 0
		BEGIN
			PRINT 'PHUONG TRINH CO NGHIEM KEP LA: ' + CONVERT(CHAR,-@B/2*@A)
			RETURN 0
		END
		ELSE
			PRINT 'PHUONG TRINH VO NGHIEM'
			RETURN 0
	END
END
GO
EXEC SPPTBAC2 1,4,1

--BAI 7

CREATE PROC SPDIEMSV @MSSV CHAR(8)
AS
BEGIN
	SELECT DIEM FROM DIEM WHERE MASV = @MSSV
END
GO
EXEC SPDIEMSV 'SV1'

--BAI 8

ALTER PROC SPNHAPDIEM @MSSV CHAR(8), @MAMH CHAR(8), @LAN INT, @HOCKY INT, @DIEM FLOAT
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM SINHVIEN WHERE MASV = @MSSV)
	BEGIN
		PRINT 'KHONG TIM THAY SINH VIEN CO MA SO: ' + @MSSV
		RETURN 0
	END
	IF NOT EXISTS (SELECT * FROM MONHOC WHERE MAMH = @MAMH)
	BEGIN
		PRINT 'KHONG TIM THAY MON HOC CO MA SO: ' + @MAMH
		RETURN 0
	END
	IF EXISTS (SELECT * FROM DIEM WHERE MASV = @MSSV AND MAMH = @MAMH)
	BEGIN
		PRINT 'SINH VIEN DA CO DIEM MON HOC NAY'
		RETURN 0
	END
	INSERT INTO DIEM (MASV,MAMH,LAN,HOCKY,DIEM) VALUES (@MSSV,@MAMH,@LAN,@HOCKY,@DIEM)
END
GO
EXEC SPNHAPDIEM 'SV3','MT',1,2,10

--BAI 9
CREATE PROC SPDIEMLOP @MALOP CHAR(8)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM LOP WHERE MALOP = @MALOP)
	BEGIN
		PRINT 'KHONG TIM THAY MA LOP: '+ @MALOP
		RETURN 0
	END
	ELSE
	BEGIN
		SELECT DIEM FROM DIEM WHERE DIEM.MASV IN (SELECT SINHVIEN.MASV FROM SINHVIEN INNER JOIN LOP ON 
												SINHVIEN.MALOP = LOP.MALOP
												WHERE LOP.MALOP = @MALOP)
	END
END
GO
SELECT * FROM LOP
SELECT * FROM SINHVIEN
EXEC SPDIEMLOP 'A'
--BAI 10

CREATE PROC SPTENMON @MAV CHAR(8)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM MONHOC WHERE MAMH = @MAV)
	BEGIN
		PRINT 'KHONG TIM THAY MA MON HOC: ' + @MAV
		RETURN
	END
	ELSE
	BEGIN
		SELECT TENMH FROM MONHOC WHERE MAMH = @MAV
		RETURN
	END
END
GO
EXEC SPTENMON 'MAV'

--BAI 11
ALTER PROC SPTENMON1 @MAMH CHAR(8)
AS
BEGIN
	IF @MAMH = 'MAV'
	BEGIN
		PRINT 'ANH VAN'
		RETURN
	END
	IF @MAMH = 'MAV'
	BEGIN
		PRINT N'KTCT'
		RETURN
	END
	IF @MAMH = 'MKTCT'
	BEGIN
		PRINT 'KINH TE CHINH TRI'
		RETURN
	END
	IF @MAMH = 'ML'
		RETURN N'LY'
	IF @MAMH = 'MMT'
	BEGIN
		PRINT 'MANG MAY TINH'
		RETURN
	END
	IF @MAMH = 'MT'
	BEGIN
		PRINT 'TOAN'
		RETURN
	END
	IF @MAMH = 'MTHDC'
	BEGIN
		PRINT 'TIN HOC DAI CUONG'
		RETURN
	END
	ELSE
		PRINT 'KHONG TIM THAY MA'
END
GO
EXEC SPTENMON1 'MAV'
 

ALTER PROC TENMON2 @MAMH CHAR(8)
AS
BEGIN
	SELECT 
	CASE @MAMH 
	WHEN 'MAV' THEN N'ANH VAN'
	WHEN 'MKTCT' THEN N'KINH TE CHINH TRI'
	WHEN 'MKTLT' THEN N'KY THUAT LAP TRINH'
	WHEN 'ML' THEN N'LY'
	WHEN 'MMMT' THEN N'MANG MAY TINH'
	WHEN 'MT' THEN N'TOAN'
	WHEN 'MTHDC' THEN N'TIN HOC DAI CUONG'
	END N'KHONG CO MA MON NAY'
END
GO
EXEC TENMON2 'MAV'

--BAI 12
ALTER PROC SPDTB @MSSV CHAR(8)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM SINHVIEN WHERE MASV = @MSSV)
	BEGIN
		PRINT 'KHONG TIM THAY MA SINH VIEN: ' + @MSSV
		RETURN
	END
	IF EXISTS (SELECT * FROM SINHVIEN WHERE MASV = @MSSV)
	BEGIN
		IF (SELECT COUNT(MAMH) FROM DIEM WHERE MASV = @MSSV) != (SELECT COUNT(MAMH) FROM MONHOC)
		BEGIN
			PRINT 'SINH VIEN KHONG DU MON HOC DE TINH DIEM TRUNG BINH'
			RETURN
		END
		ELSE
		BEGIN
			SELECT AVG(DIEM) AS DTB FROM DIEM WHERE MASV = @MSSV
		END	
	END

END
GO
EXEC SPDTB 'SV1'

--BAI 13
CREATE PROC SPMHTOP1 
AS
BEGIN
	SELECT TOP (1) WITH TIES MAMH FROM DIEM
	GROUP BY MAMH
	ORDER BY COUNT(MASV) DESC
END
EXEC SPMHTOP1


 --BAI 14
ALTER PROC SPSUAMASV @OLDMSSV CHAR(8), @NEWMSSV CHAR(8)
 AS
 BEGIN
	
	SELECT * INTO TEMP_SV FROM SINHVIEN
	WHERE MASV = @OLDMSSV

	SELECT * INTO TEMP_DIEM FROM DIEM
	WHERE MASV = @OLDMSSV

	DELETE FROM DIEM
	WHERE MASV = @OLDMSSV

	DELETE FROM SINHVIEN
	WHERE MASV = @OLDMSSV

	UPDATE TEMP_SV
	SET MASV = @NEWMSSV

	UPDATE TEMP_DIEM
	SET MASV = @NEWMSSV

	INSERT INTO SINHVIEN
	SELECT * FROM TEMP_SV
	DROP TABLE TEMP_SV

	INSERT INTO DIEM
	SELECT * FROM TEMP_DIEM
	DROP TABLE TEMP_DIEM

 END
 GO
 EXEC SPSUAMASV 'SV2','SV02'

 SELECT * FROM DIEM

 --BAI 15
CREATE PROC SPSUAMAMH @OLDMAMH CHAR(8), @NEWMAMH CHAR(8)
AS
BEGIN
	
	SELECT * INTO TEMP_MON
	FROM MONHOC
	WHERE MAMH = @OLDMAMH

	SELECT * INTO TEMP_DIEM
	FROM DIEM
	WHERE MAMH = @OLDMAMH

	DELETE FROM MONHOC
	WHERE MAMH = @OLDMAMH

	DELETE FROM DIEM
	WHERE MAMH = @OLDMAMH

	UPDATE TEMP_MON
	SET MAMH = @NEWMAMH

	UPDATE TEMP_DIEM
	SET MAMH = @NEWMAMH

	INSERT INTO MONHOC
	SELECT * FROM TEMP_MON
	DROP TABLE TEMP_MON

	INSERT INTO DIEM
	SELECT * FROM TEMP_DIEM
	DROP TABLE TEMP_DIEM

END
GO
EXEC SPSUAMAMH 'MMT','MMMT'
SELECT * FROM MONHOC
SELECT * FROM DIEM
