USE QLSV1
GO
--CAU 1
CREATE PROC SP_XUATLOP
AS
BEGIN
	--C1
	SELECT LOP.MALOP,LOP.TENLOP FROM LOP LEFT JOIN SINHVIEN ON LOP.MALOP = SINHVIEN.MALOP	
	WHERE SINHVIEN.MALOP IS  NULL
END
GO
EXEC SP_XUATLOP
--C2
SELECT MALOP,TENLOP FROM LOP WHERE LOP.MALOP  NOT IN (SELECT MALOP FROM SINHVIEN)

--CAU 2
CREATE PROC SP_XUATSISO
AS 
BEGIN
	SELECT LOP.TENLOP,LOP.MALOP,COUNT(SINHVIEN.MASV) AS SISO FROM LOP  JOIN  SINHVIEN ON LOP.MALOP = SINHVIEN.MALOP
	GROUP BY LOP.MALOP,LOP.TENLOP
END
GO
EXEC SP_XUATSISO
--CAU 3
CREATE PROC SP_SISONAMNU @MALOP CHAR(8)
AS
BEGIN
		SELECT LOP.MALOP,LOP.TENLOP, 
		SUM(CASE(PHAI) WHEN 'nam' then 1 else 0 end) AS SISONAM,
		SUM(CASE(PHAI) WHEN 'nu' then 1 else 0 end) AS SISONU
		FROM LOP JOIN SINHVIEN ON LOP.MALOP = SINHVIEN.MALOP
		WHERE LOP.MALOP = @MALOP
		GROUP BY LOP.MALOP,LOP.TENLOP
END
GO
EXEC SP_SISONAMNU 'HTTT2'

--CAU 4
ALTER PROC SP_THEMMH @MAMH CHAR(8),@TENMH CHAR(30), @SOTIET_LT INT, @SOTIET_TH INT
AS
BEGIN

	IF EXISTS (SELECT * FROM MONHOC WHERE MAMH = @MAMH OR TENMH = @TENMH)
	BEGIN
		PRINT 'DA CO MA MON HOC ' + @MAMH +'HOAC TEN MON HOC ' +@TENMH
		RETURN
	END
	INSERT INTO MONHOC(MAMH,TENMH,SOTIET_LT,SOTIET_TH) VALUES (@MAMH,@TENMH,@SOTIET_LT,@SOTIET_TH)

END
GO
EXEC SP_THEMMH 'MKTPM','KIEM THU PHAN MEM',60,0


SELECT * FROM MONHOC
DELETE FROM MONHOC WHERE MAMH = 'MKTPM'

--BAI5

ALTER PROC SP_SUADIEM @MASV CHAR(8),@MAMH CHAR(8),@DIEMSUA FLOAT
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM SINHVIEN WHERE MASV = @MASV)
	BEGIN
		PRINT 'KHONG TIM THAY MA SINH VIEN ' + @MASV
		RETURN
	END
	IF NOT EXISTS (SELECT * FROM MONHOC WHERE MAMH = @MAMH)
	BEGIN
		PRINT 'KHONG TIM THAY MA MON HOC ' + @MAMH
		RETURN
	END
	IF @DIEMSUA < 0 OR @DIEMSUA > 10
	BEGIN
		PRINT 'DIEM NHAP KHONG HOP LE'
		RETURN
	END

	IF  EXISTS (SELECT * FROM SINHVIEN WHERE MASV = @MASV)
	BEGIN
		IF  NOT EXISTS (SELECT * FROM MONHOC WHERE MAMH = @MAMH)
		BEGIN
			PRINT 'SV KHONG CO MA MON DE SUA'
			RETURN
		END
		ELSE
			UPDATE DIEM
			SET DIEM = @DIEMSUA
			WHERE MAMH = @MAMH AND MASV = @MASV
			RETURN
			
	END
END
GO
EXEC SP_SUADIEM 'SV3','MMMT',10
SELECT * FROM DIEM
SELECT * FROM MONHOC
--BAI 6A
CREATE PROC SP_XOAMHA @MAMH CHAR(8)
AS
BEGIN
	IF EXISTS (SELECT * FROM DIEM WHERE MAMH = @MAMH)
	BEGIN
		PRINT 'DA CO SINH VIEN DANG KY MON NAY'
		RETURN
	END
	DELETE FROM MONHOC WHERE MAMH = @MAMH

END
GO
EXEC SP_XOAMHA 'ML'

--BAI 6B
ALTER PROC SP_XOAMHB @MAMH CHAR(8)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM DIEM WHERE MAMH = @MAMH)
	BEGIN
		DELETE FROM MONHOC WHERE MAMH = @MAMH
		RETURN
	END
	ELSE
	BEGIN
		DELETE FROM DIEM WHERE MAMH = @MAMH
		DELETE FROM MONHOC WHERE MAMH = @MAMH
	END
END
GO
EXEC SP_XOAMHB 'MKTPM'

--BAI 1
CREATE PROC SP_SVCHUADK 
AS
BEGIN
	SELECT * FROM SINHVIEN LEFT JOIN DIEM ON DIEM.MASV = SINHVIEN.MASV
	WHERE DIEM.MAMH IS NULL
END
GO
EXEC SP_SVCHUADK
SELECT MASV,TEN FROM SINHVIEN WHERE SINHVIEN.MASV NOT IN (SELECT MASV FROM DIEM)
--BAI2
CREATE PROC SP_HOANTATCT
AS
BEGIN
	SELECT MASV, HO, TEN
    FROM SINHVIEN
    WHERE NOT EXISTS (
        SELECT *
        FROM MONHOC
        WHERE MAMH NOT IN (SELECT MAMH FROM DIEM WHERE MASV = SINHVIEN.MASV)
    )
END
GO
EXEC SP_HOANTATCT
--BAI3
CREATE PROC SP_XOASINHVIENX @MSV CHAR(8)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM SINHVIEN WHERE MASV = @MSV)
	BEGIN
		PRINT ('KHONG CO MA SINH VIEN NAY')
		RETURN
	END
	IF EXISTS (SELECT * FROM SINHVIEN WHERE MASV = @MSV)
	BEGIN
		IF NOT EXISTS (SELECT * FROM DIEM WHERE MASV = @MSV)
		BEGIN
			DELETE FROM SINHVIEN WHERE MASV = @MSV
			RETURN
		END
		ELSE
			PRINT 'SINH VIEN DA CO KQ HOC TAP, KHONG THE XOA'
	END
	
END
GO
EXEC SP_XOASINHVIENX 'SV5'
